on:
  check_run:
    types: [requested_action]
  push:
    branches:
      - master

name: Deploy frontend to platform 3

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        deployment: [PLATFORM3]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.${{ matrix.deployment }}_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.${{ matrix.deployment }}_AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-3
    
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      
    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    
    - name: Install dependencies
      working-directory: packages/web
      run: yarn install
      
    - name: Build frontend
      working-directory: packages/web
      env:
        GRAPHQL_API_URL: ${{ secrets.${{ matrix.deployment }}_GRAPHQL_API_URL }}
      run: |
        yarn build:production
        
    - name: Deploy frontend to s3
      working-directory: packages/web
      env:
        BUCKET_NAME: ${{ secrets.${{ matrix.deployment }}_BUCKET_NAME }}
      run: aws s3 sync ./build/ s3://$BUCKET_NAME --delete
